version: '3'
services:
  caddy:
    image: abiosoft/caddy:0.10.12
    container_name: caddy
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/Caddyfile:/etc/Caddyfile
      - caddy-data:/root/.caddy
  rancher:
    container_name: rancher
    image: rancher/server:stable
    volumes: 
      - rancher-mysql:/var/lib/mysql
    restart: unless-stopped
volumes: 
  rancher-mysql:
    driver: local
  caddy-data:
    driver: local
    
