version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    container_name: caddy
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/cloud_durian/rancher/Caddyfile:/etc/Caddyfile
      - /home/cloud_durian/rancher/.caddy:/root/.caddy
  rancher:
    container_name: rancher
    image: rancher/server:stable
    command: --db-host 10.148.0.3 --db-port 3306 --db-user rancher --db-pass durian2017 --db-name rancher
    restart: unless-stopped
