version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    container_name: caddy
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/cloud_durian/rancher/Caddyfile:/etc/Caddyfile
      - /home/cloud_durian/rancher/.caddy:/root/.caddy
  rancher:
    container_name: rancher
    image: rancher/server:stable
    volumes:
      - /home/cloud_durian/rancher/mysql:/var/lib/mysql
    restart: unless-stopped
